version: "3"

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: sample
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql

volumes:
  postgres:
